---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-teste
  template:
    metadata:
      labels:
        app: app-teste
    spec:
      containers:
      - name: webserver-simple
        image: nginx
        ports:
        - containerPort: 8080
